# Generated by Django 4.2.15 on 2024-08-28 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LowLevelDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LLDs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RadioSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lld', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radio_sites', to='main.lowleveldesign')),
            ],
        ),
        migrations.CreateModel(
            name='StaticRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.GenericIPAddressField()),
                ('next_hop', models.GenericIPAddressField()),
                ('radio_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='static_routes', to='main.radiosite')),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lld', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.lowleveldesign')),
            ],
        ),
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lld', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routers', to='main.lowleveldesign')),
                ('o_and_m_route', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='router_o_and_m', to='main.staticroute')),
                ('tdd_route', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='router_tdd', to='main.staticroute')),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('radioSite', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.radiosite')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physicalInterfaces', to='main.router')),
            ],
        ),
        migrations.CreateModel(
            name='ManagementInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('vlan', models.IntegerField()),
                ('connectedTo', models.GenericIPAddressField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('physicalInterface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logicalInterfaces_management', to='main.physicalinterface')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Interface4G',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('vlan', models.IntegerField()),
                ('connectedTo', models.GenericIPAddressField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('physicalInterface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logicalInterfaces_4g', to='main.physicalinterface')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Interface3G',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('vlan', models.IntegerField()),
                ('connectedTo', models.GenericIPAddressField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('physicalInterface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logicalInterfaces_3g', to='main.physicalinterface')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Interface2G',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('vlan', models.IntegerField()),
                ('connectedTo', models.GenericIPAddressField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('physicalInterface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logicalInterfaces_2g', to='main.physicalinterface')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
