# Generated by Django 5.0.7 on 2024-08-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_client_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='content',
            field=models.TextField(),
        ),
    ]
