# Generated by Django 4.2.15 on 2024-08-08 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_script_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalinterface',
            name='radioSite',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.radiosite'),
        ),
        migrations.AlterField(
            model_name='lowleveldesign',
            name='client',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
