# Generated by Django 4.2.15 on 2024-08-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_physicalinterface_radiosite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lowleveldesign',
            name='client',
        ),
        migrations.AddField(
            model_name='lowleveldesign',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
