# Generated by Django 4.2.15 on 2024-08-15 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_lowleveldesign_client_lowleveldesign_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='LowLevelDesign_Co_trans',
            fields=[
                ('lowleveldesign_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.lowleveldesign')),
                ('o_and_m', models.GenericIPAddressField()),
                ('TDD', models.GenericIPAddressField()),
            ],
            bases=('main.lowleveldesign',),
        ),
    ]
