# Generated by Django 4.2.15 on 2024-08-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_lowleveldesign_co_trans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowleveldesign_co_trans',
            name='TDD',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lowleveldesign_co_trans',
            name='o_and_m',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
