# Generated by Django 4.2.15 on 2024-08-22 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_script_created_at_script_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Scripts', to=settings.AUTH_USER_MODEL),
        ),
    ]
