# Generated by Django 4.2.15 on 2024-08-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_script_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lowleveldesign_co_trans',
            name='TDD_next',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lowleveldesign_co_trans',
            name='o_and_m_next',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
