# Generated by Django 4.2.15 on 2024-08-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_lowleveldesign_co_trans_tdd_next_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowleveldesign_co_trans',
            name='TDD',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lowleveldesign_co_trans',
            name='TDD_next',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lowleveldesign_co_trans',
            name='o_and_m',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lowleveldesign_co_trans',
            name='o_and_m_next',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
