# Generated by Django 4.2.15 on 2024-08-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_lowleveldesign_co_trans_tdd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowleveldesign_co_trans',
            name='TDD',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lowleveldesign_co_trans',
            name='TDD_next',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lowleveldesign_co_trans',
            name='o_and_m',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lowleveldesign_co_trans',
            name='o_and_m_next',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
