# Generated by Django 4.2.15 on 2024-08-25 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0012_alter_lowleveldesign_co_trans_tdd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='script',
            name='user',
        ),
        migrations.AddField(
            model_name='lowleveldesign',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='lowleveldesign',
            name='lld',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LLDs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='script',
            name='lld',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.lowleveldesign'),
        ),
    ]
