# Generated by Django 4.2.15 on 2024-08-25 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_script_user_lowleveldesign_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lowleveldesign',
            old_name='lld',
            new_name='user',
        ),
    ]
