# Generated by Django 4.2.15 on 2024-08-25 14:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_lld_lowleveldesign_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
